# inspired by https://github.com/microsoft/rushstack/issues/2057#issuecomment-902362602
name: '@nicktomlin/rush-playground-ci'

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RUSH_BOT_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - name: Rush CLI
        run: npm install -g @microsoft/rush@5.50.0

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Rush Test
        run: node common/scripts/install-run-rush.js test

      - name: Rush Build
        run: node common/scripts/install-run-rush.js build

      - name: Commit Dist
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -a -m 'Updated dists' || echo "No changes to commit"
          git push

      # Can't be in a separate job as we need the results of any build to be included in
      # any published module.
      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: node common/scripts/install-run-rush.js publish -p -b main --include-all --set-access-level=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
